backend:
  name: git-gateway
  # name: test-repo
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

site_url: https://gautamn.netlify.app

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.json"
        description: "General Site Settings"
        fields:
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {
                  label: "Number of posts on frontpage",
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: "Default Author", name: author, widget: string }
              - {
                  label: "Default Thumbnail",
                  name: thumb,
                  widget: image,
                  class: "thumb",
                  required: false,
                }
      - name: "websiteStaticContent"
        label: "Website Static Content"
        file: "_data/websiteStaticContent.json"
        description: "Static Data of the website like text, images"
        fields:
          - { label: "Position", name: "position", widget: "string", default: "Frontend Developer & Designer" }
          - { label: "Company", name: "company", widget: "string" , default: "Bidchat" }
          - { label: "About Me", name: "aboutMe", widget: "markdown", default: "Hi, I am Gautam Naik"}
          - { label: "Birthdate", name: "bday", widget: "string" , default: "2nd May 1994" }
          - { label: "Email", name: "email", widget: "string" , default: "gautamnaik1994@gmail.com" }
          - { label: "Location", name: "location", widget: "string" , default: "Panaji-Goa" }
          # Socail Links
          - { label: "About Me Image", name: "aboutMeImage", widget: "image" }
          - { label: "CV", name: "cv", widget: "file" }

  - name: "skills"
    label: "Skills"
    folder: "_data/skills"
    slug: 'skill-{{title}}'
    editor:
      preview: false
    create: true
    description: "Skills Info"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Value", name: "value", widget: "number" }
      - label: "Details"
        name: "details"
        widget: "list"
        allow_add: true
        summary: "{{fields.key}} - {{fields.value}}"
        fields:
          - label: Key
            name: key
            widget: string
            default: "Languages"
          - label: Value
            name: value
            widget: string
            default: "HTML, CSS"
  - name: "projects"
    label: "Projects"
    folder: "_data/projects"
    editor:
      preview: false
    create: true
    slug: 'project-{{title}}'
    description: "Projects Info"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Details"
        name: "details"
        widget: "list"
        allow_add: true
        summary: "{{fields.key}} - {{fields.value}}"
        fields:
          - label: Key
            name: key
            widget: string
            default: "Languages"
          - label: Value
            name: value
            widget: string
            default: "HTML, CSS"
  - name: "workExperience"
    label: "Work Experience"
    folder: "_data/workExperience"
    slug: 'workExperience-{{title}}'
    editor:
      preview: false
    create: true
    description: "Work Experience Info"
    fields:
      - { label: "Company Name", name: "title", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Time Range", name: "timeRange", widget: "string" }
      - { label: "Responsibilities", name: "responsibilities", widget: "markdown" }
