backend:
  # name: git-gateway
  name: test-repo
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://gautamn.netlify.app

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: '_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Position', name: 'position', widget: 'string' }
          - { label: 'About Me', name: 'about_me', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }
  - name: 'skills'
    label: 'Skills'
    folder: 'skills'
    editor:
      preview: false
    create: true
    description: 'Skills Info'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Value', name: 'value', widget: 'number' }
      - label: 'Details'
        name: 'details'
        widget: 'list'
        allow_add: true
        summary: '{{fields.key}} - {{fields.value}}'
        fields:
          - label: Key
            name: key
            widget: string
            default: 'Languages'
          - label: Value
            name: value
            widget: string
            default: 'HTML, CSS'
  - name: 'projects'
    label: 'Projects'
    folder: 'projects'
    editor:
      preview: false
    create: true
    description: 'Projects Info'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Value', name: 'value', widget: 'number' }
      - label: 'Details'
        name: 'details'
        widget: 'list'
        allow_add: true
        summary: '{{fields.key}} - {{fields.value}}'
        fields:
          - label: Key
            name: key
            widget: string
            default: 'Languages'
          - label: Value
            name: value
            widget: string
            default: 'HTML, CSS'
